apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app-hello-world
          image: gcr.io/aihubble/python-app:GITHUB_SHA # actionsで指定したpuahのイメージに合わせる必要あり
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
    - port: 80
      targetPort: 8080
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: python-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/configuration-snippet: |
#       more_set_headers "X-Frame-Options: Deny";
#       more_set_headers "X-Xss-Protection: 1; mode=block";
#       more_set_headers "X-Content-Type-Options: nosniff";
# spec:
#   rules:
#     - host: microservices.cloudageskill.com
#       http:
#         paths:
#           - backend:
#               service:
#                 name: python-app-service
#                 port:
#                   number: 8080
#             path: /
#             pathType: ImplementationSpecific
