apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app-deplyment-label # Deployment自体のラベル
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app # ポッドのラベルを指定(template.metadata.labels.appと一致)
  template:
    metadata:
      labels:
        app: python-app # ポッドのラベル
    spec:
      containers:
        - name: python-app-hello-world
          image: gcr.io/PROJECT_ID/IMAGE:GITHUB_SHA # actionsで指定したpuahのイメージに合わせる必要あり
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
    - port: 80
      targetPort: 8080
